#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$PATH

######sjc add for ipc

ln -s /usr/lib/libcurl.so /usr/lib/libcurl.so.4
ln -s /usr/lib/libg7xx.so /usr/lib/libg7xx.so.0
ln -s /usr/lib/libzbar.so /usr/lib/libzbar.so.0
ln -s /usr/lib/libssh2.so /usr/lib/libssh2.so.1
ln -s /usr/lib/libsqlite3.so /usr/lib/libsqlite3.so.0
ln -s /usr/lib/libssl.so /usr/lib/libssl.so.1.0.0
ln -s /usr/lib/libcrypto.so /usr/lib/libcrypto.so.1.0.0


cp /home/web/productionread.inf /tmp


amba_debug -g 13 -d 1
amba_debug -g 14 -d 0
amba_debug -g 91 -d 0
amba_debug -g 92 -d 1
amba_debug -g 14 -d 1
amba_debug -g 13 -d 0
amba_debug -g 91 -d 1
amba_debug -g 92 -d 0
amba_debug -g 92 -d 1


init.sh --ov4689



